In [1]:
import numpy as np

a = np.random.randn(5)
# creates an array of specified shape and 
# fills it with random values as per standard normal distribution

In [2]:
print(a)

[ 1.91039452  0.62097796  0.88589665 -0.71631952  1.37894607]


In [3]:
print(a.shape)
# a is rank 1 matrix

(5,)


In [4]:
print(a.T)
# Transpose

[ 1.91039452  0.62097796  0.88589665 -0.71631952  1.37894607]


In [5]:
print(np.dot(a, a.T))

7.23463965391


In [7]:
a = np.random.randn(5, 1)
print(a)

[[ 0.69582608]
 [-0.83958707]
 [-0.14155515]
 [-1.07021916]
 [-0.15170675]]


In [8]:
print(a.T)

[[ 0.69582608 -0.83958707 -0.14155515 -1.07021916 -0.15170675]]


In [9]:
print(np.dot(a, a.T))

[[ 0.48417394 -0.58420658 -0.09849776 -0.74468641 -0.10556151]
 [-0.58420658  0.70490645  0.11884787  0.89854217  0.12737102]
 [-0.09849776  0.11884787  0.02003786  0.15149503  0.02147487]
 [-0.74468641  0.89854217  0.15149503  1.14536906  0.16235947]
 [-0.10556151  0.12737102  0.02147487  0.16235947  0.02301494]]


**Note:** Use 5x1 matrix instead of rank 1 array

**Don't Use:**  
a = np.random.randn(5)  
Here, a.shape = (5,)

**Use:**  
a = np.random.randn(5,1)  
Here, a.shape = (5,1)  
*column vector*  
  
a = np.random.randn(1,5)  
Here, a.shape = (1,5)  
*row vector*

Use assertion statements to check dimensions  
assert(a.shape == (5, 1))

To reshape rank 1 arrays:  
a = a.reshape((5,1))